title: coo11's front page

images:
  # - https://tva2.sinaimg.cn/large/007HLCaply1g3txfml208j31hc0u0agm.jpg
  # - https://tva3.sinaimg.cn/large/007HLCaply1g6yyg0k3u6j315o0the1w.jpg # å¶åƒå¤§å¸ˆ
  - https://tva4.sinaimg.cn/large/007HLCaply1g3txganifkj31hc0u07nc.jpg # Steins;Gate 0 CG
  - https://tva1.sinaimg.cn/large/007HLCaply1g3txg3ge70j31jk13a7ea.jpg # èŠ±ã®åº­ #JK #Yuri
  # - https://tva1.sinaimg.cn/large/007HLCaply1g3txfykvg5j31jk0yq7bb.jpg # ä¸‡è±¡ç‰©è¯­
  - https://tva1.sinaimg.cn/large/be297bc5gy1gi8rdnnyomj21hc0tlnpd.jpg # ç¾é£Ÿæ®¿å ‚æ°´ç€

bookmark:
  - name: Google
    url: https://www.google.com/ncr
    favicon: google.png
  - name: Gmail
    url: https://inbox.google.com/
    favicon: gmail.png
  - name: QQé‚®ç®±
    url: https://mail.qq.com
    favicon: qqmail.png
  - name: Outlook
    url: https://outlook.live.com/mail/0/inbox
    favicon: outlook.png
  # - name: Google Earth
  #   url: https://earth.google.com/web/
  # - name: Google Maps
  #   url: https://www.google.com/maps/
  # - name: YandexMail
  #   url: https://mail.yandex.com/
  - name: GitHub
    url: https://github.com
    favicon: github.png
  - name: Wikipedia
    url: https://zh.wikipedia.org/zh-hans/Wikipedia:%E9%A6%96%E9%A1%B5
    favicon: wiki.png
  - name: Notion
    url: https://www.notion.so/70/
    favicon: notion.png
  - name: Youtube
    url: https://www.youtube.com
    favicon: youtube.png
  - name: å“”å“©å“”å“©
    url: https://www.bilibili.com
    favicon: bilibili.png
  - name: Telegram
    url: https://web.telegram.org/k/
    #   url: https://web.telegram.org/z/
    favicon: telegram.png
  - name: åšæœäº‘
    url: https://www.jianguoyun.com
    favicon: jianguoyun.png
  - name: ç™¾åº¦ç½‘ç›˜
    url: https://pan.baidu.com/disk/home
    favicon: baidunetdisk.png
  - name: DeepL
    url: https://www.deepl.com/translator
    favicon: deepl.png
  - name: GIR
    url: https://coo11.github.io/gir/
    favicon: gir.png

  - category: Shortcut
  - name: Rentry.co
    url: https://rentry.co
    favicon: rentryco.png
  - name: Telegraph
    url: https://telegra.ph
    favicon: telegraph.png
  - name: <b>More....</b>
    newTab: true
    url: https://rentry.co/webservice

  - category: SNS
  - name: çŸ¥ä¹
    url: https://www.zhihu.com
    favicon: zhihu.png
  - name: Twitter
    url: https://twitter.com
    favicon: twitter.png
  - name: å¾®åš
    url: https://weibo.com
    favicon: weibo.png
  - name: è™ç‰™
    url: https://www.huya.com
    favicon: huya.png
  - name: æ–—é±¼
    url: https://www.douyu.com
    favicon: douyu.png
  - name: Twitch
    url: https://www.twitch.tv
    favicon: twitch.png

  - category: Search
  - name: Yandex æœå›¾
    url: https://yandex.com/images/
    favicon: yandeximage.png
  - name: Google å›¾ç‰‡
    url: https://images.google.com
    favicon: google.png
  - name: ç™¾åº¦è¯†å›¾
    url: https://image.baidu.com/?fr=shitu
    favicon: baidu.png
  # - name: IQDB
  #   url: https://iqdb.org/
  #   favicon: iqdb.png
  - name: SauceNAO
    url: https://saucenao.com
    favicon: saucenao.png
  - name: ascii2d
    url: https://ascii2d.net
    favicon: ascii2d.png
  - name: WolframAlpha
    url: https://www.wolframalpha.com/
    favicon: wolframalpha.png
  - name: Twitter é«˜çº§æœç´¢
    url: https://twitter.com/search-advanced
    favicon: twitter.png
  - name: Bing
    url: https://www.bing.com
    favicon: bing.png
  - name: Yahoo
    url: https://search.yahoo.com
    favicon: yahoo.png
  - name: Google å­¦æœ¯
    url: https://scholar.google.com
    favicon: googlescolar.png
  - name: Mag[i]
    url: https://magi.com
  - name: WAIT
    url: https://trace.moe

  - category: Community
  - name: NGA
    url: https://bbs.nga.cn
    favicon: nga.png
  - name: V2EX
    url: https://v2ex.com
    favicon: v2ex.png
  - name: reddit
    url: https://www.reddit.com
    favicon: reddit.png
  # - name: 4chan
  #   url: https://www.4chan.org
  # - name: Ğ”Ğ²Ğ°.Ñ‡
  #   url: https://2ch.hk
  - name: Steam
    url: https://steamcommunity.com
    favicon: steam.png
  - name: PCbeta
    url: http://bbs.pcbeta.com/forum.php
    favicon: pcbeta.png
  - name: Aå²›
    url: https://adnmb.com
  - name: Stage1
    url: https://bbs.saraba1st.com/2b/forum.php
  # - name: ExcelHome
  #   url: http://club.excelhome.net/forum.php
  - name: å¾çˆ±ç ´è§£
    url: https://www.52pojie.cn
  - name: ç¦åˆ©å§
    url: https://lao4g.com

  - category: ACG
  - name: ç•ªç»„è®¡åˆ’
    url: https://bgm.tv/group/a
    favicon: bangumi.png
  - name: AcFun
    url: https://www.acfun.cn
    favicon: acfun.png
  # - name: çˆ±æ‹åŠ¨æ¼«
  #   url: https://www.kisssub.org/
  - name: Pixiv
    url: https://www.pixiv.net
    favicon: pixiv.png
  - name: åŠ¨æ¼«ä¹‹å®¶
    url: https://manhua.dmzj.com
  - name: å¤©ä½¿åŠ¨æ¼«
    url: https://www.tsdm39.net/forum.php
  - name: èŒå¨˜ç™¾ç§‘
    url: https://zh.moegirl.org.cn/Mainpage
  - name: ğŸµèŒ¶é¦†
    url: https://bbs.imoutolove.me/thread.php?fid-9.html
  - name: <b>More....</b>
    newTab: true
    url: https://rentry.co/acg

  - category: Dev
  - name: StackOverflow
    url: https://stackoverflow.com
    favicon: stackoverflow.png
  - name: SuperUser
    url: https://superuser.com
    favicon: superuser.png
  - name: MDN
    url: https://developer.mozilla.org/zh-CN/docs/Learn
    favicon: mdn.png
  - name: RegExr
    url: https://regexr.com
    favicon: regexr.png
  - name: JSFiddle
    url: https://jsfiddle.net
    favicon: jsfiddle.png
  - name: musicForProgramming
    url: https://musicforprogramming.net
    favicon: musicforprogramming.png
  - name: GitLab
    url: https://gitlab.com
    favicon: gitlab.png
  - name: Gitee
    url: https://gitee.com
    favicon: gitee.png
  - name: Carbon
    url: https://carbon.now.sh
  - name: HTML Cleaner
    url: https://html-cleaner.com
  - name: HTML2MD
    url: https://tool.lu/markdown/
  - name: <b>More....</b>
    newTab: true
    url: https://rentry.co/idev

  - category: Utils
  - name: GoogleVoice
    url: https://voice.google.com/messages
    favicon: googlevoice.png
  - name: Textnow
    url: https://www.textnow.com/messaging
    favicon: textnow.png
  - name: Inoreader
    url: https://jp.inoreader.com/language/chinese-simplified
    favicon: inoreader.png
  - name: UnicodeTable
    url: https://unicode-table.com/cn/
    favicon: unicodetable.png
  - name: Dropmail
    url: https://dropmail.me/zh/
  - name: TableConvert
    url: https://tableconvert.com
  - name: InternetArchive
    url: https://archive.org/web/
  - name: Archive.today
    url: https://archive.is
  - name: AriaNg
    # url: http://ariang.mayswind.net/latest
    url: http://p3terx.gitee.io/ariang/#!/settings/rpc/set/http/127.0.0.1/6800/jsonrpc
  - name: Sketchpad
    url: https://sketch.io/sketchpad/?lang=zh
    favicon: sketchpad.png
  - name: PaperSizes
    url: https://papersizes.io
    favicon: papersizes.png
  - name: Online Convert
    url: https://www.online-convert.com
    favicon: onlineconvert.png
  - name: CloudConvert
    url: https://cloudconvert.com
    favicon: cloudconvert.png
  - name: iLovePDF
    url: https://www.ilovepdf.com/zh-cn
    favicon: ilovepdf.png

  - category: Shopping
  - name: äº¬ä¸œ
    url: https://search.jd.com
    favicon: jingdong.png
  - name: æ·˜å®
    url: https://search.taobao.com
    favicon: taobao.png
  - name: 1688
    url: https://search.1688.com
    favicon: 1688.png
  - name: Amazon
    url: https://www.amazon.co.jp
    favicon: amazon.png

  - category: Image
  - name: PixFix
    url: https://zh.pixfix.com
    favicon: pixfix.png
  - name: waifu2x
    url: https://waifu2x.booru.pics/
    # Alternatives
    # https://waifu2x.me/
    # https://waifu2x.udp.jp/
  - name: TinyPNG
    url: https://tinypng.com
  - name: Watermark
    url: http://watermark.dxcweb.com/
    favicon: pic.png
  - name: EZGIF
    url: https://ezgif.com
  - name: ImgOps
    url: https://imgops.com
  - name: Unsplash
    url: https://unsplash.com/
    favicon: unsplash.png
  - name: åŠ¨å›¾åŸºåœ°
    url: https://www.asqql.com/g/

  - category: Cloud Service
  - name: iCloud
    url: https://www.icloud.com/
    favicon: icloud.png
  - name: MEGA
    url: https://mega.nz/fm/
    favicon: mega.png
  - name: è“å¥äº‘
    url: https://www.lanzou.com/
    favicon: lanzou.png
  - name: Wokers
    url: https://workers.cloudflare.com
    favicon: cloudflare.png
  - name: Apps Script
    url: https://script.google.com/home
    favicon: appsscript.png
  - name: GDrive
    url: https://drive.google.com/drive/my-drive
    favicon: gdrive.png
  - name: OneDrive
    url: https://onedrive.live.com
    favicon: onedrive.png

  - category: Booru
  - name: Danbooru
    url: https://danbooru.donmai.us/
    favicon: danbooru.png
  - name: Gelbooru
    url: https://gelbooru.com/
    favicon: gelbooru.png
  - name: yande.re
    url: https://yande.re/post
    favicon: yandere.png
  - name: Sankaku
    url: https://chan.sankakucomplex.com/cn/post
    favicon: sankakucomplex.png
  - name: Konachan
    url: https://konachan.com/post
    favicon: konachan.png

  - category: Calc
  - name: NumberEmpire
    url: https://zh.numberempire.com/
  - name: MathStudio
    url: http://mathstud.io/
    favicon: mathstudio.png
  - name: Desmos
    url: https://www.desmos.com/calculator?lang=zh-CN
    favicon: desmos.png
    # Alternative
    # https://www.geogebra.org/graphing
  - name: Mathway
    url: https://www.mathway.com/zh/Algebra
    favicon: mathway.png

  - category: Unclassified
  - name: Applist
    newTab: true
    url: https://rentry.co/applist
    favicon: rentryco.png
  - name: NoUse
    newTab: true
    url: https://rentry.co/sitenouse
    favicon: rentryco.png
  - name: Githubâœ‹â­
    url: https://rentry.co/githubnostar
    favicon: github.png
  - name: IMDb
    url: https://www.imdb.com/
    favicon: imdb.png
  - name: ç½‘ç›˜æœç´¢
    url: https://adzhp.cn/wang-pan-sou-suo.html
  - name: å¤©çœ¼æŸ¥
    url: https://www.tianyancha.com/
    favicon: tianyancha.png
  - name: ä¼æŸ¥æŸ¥
    url: https://www.qcc.com/
    favicon: qichacha.png
  - name: è¥¿è´´
    url: http://www.xitie.com/
  - name: æ¯”ä¸€æ¯”ä»·
    url: http://b1bj.com/
  - name: SteamDB
    url: https://steamdb.info/
    favicon: steamdb.png
  - name: Humble
    url: https://www.humblebundle.com/
    favicon: humble.png

  # - category: NSFW
  # - name: E-Hentai
  #   url: https://e-hentai.org/
  #   favicon: ehentai.png
  # - name: ExHentai
  #   url: https://exhentai.org/
  #   favicon: ehentai.png
  # - name: ç»…å£«ä»“åº“
  #   url: https://galacg.github.io/
  # - name: èŒ¶é¦†ğŸµ
  #   url: https://bbs.imoutolove.me/thread.php?fid-9.html
  # - name: ç‰ç’ƒç¥ç¤¾â›©
  #   url: https://acg.gy/
  # - name: ç´³å£«ã®åº­ğŸ©
  #   url: https://gmgard.com/
  # - name: Sukebei
  #   url: https://sukebei.nyaa.si/
  #   favicon: nyaa.png
  # - name: Nyaa
  #   url: https://nyaa.si/
  #   favicon: nyaa.png
  # - name: HVDB
  #   url: https://hvdb.me/Dashboard/
  # - name: ï¼­ï¼¡ï¼®ï¼§ï¼¡ï¼ï¼¤ï¼¢
  #   url: https://adultcomic.dbsearch.net/
  # - name: ğŸ¼Panda Backup
  #   url: https://panda.chaika.moe/
  # - name: è‰æ¦´ç¤¾åŒº
  #   url: https://t66y.com/index.php
  #   favicon: caoliu.png
  # - name: PornDude
  #   url: https://theporndude.com/zh
  #   favicon: porndude.png